package com.orm.processor;

import com.orm.annotations.GenerateRepository;
import com.orm.annotations.Table;
import com.squareup.javapoet.*;

import javax.annotation.processing.*;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.*;
import javax.lang.model.type.TypeMirror;
import javax.tools.Diagnostic;
import java.io.IOException;
import java.util.List;
import java.util.Optional;
import java.util.Set;

/**
 * Annotation Processor for @GenerateRepository.
 *
 * For every class annotated with @GenerateRepository it generates a
 * <ClassName>Repository.java that delegates to OrmSession.
 *
 * RetentionPolicy.SOURCE means the annotation is NOT in the .class file —
 * this processor reads it only during javac.
 */
@SupportedAnnotationTypes("com.orm.annotations.GenerateRepository")
@SupportedSourceVersion(SourceVersion.RELEASE_17)
public class RepositoryProcessor extends AbstractProcessor {

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {

        for (Element element : roundEnv.getElementsAnnotatedWith(GenerateRepository.class)) {

            if (element.getKind() != ElementKind.CLASS) {
                processingEnv.getMessager().printMessage(
                        Diagnostic.Kind.ERROR,
                        "@GenerateRepository must be on a class", element);
                continue;
            }

            TypeElement classElement = (TypeElement) element;
            generateRepository(classElement);
        }
        return true;
    }

    // ------------------------------------------------------------------
    private void generateRepository(TypeElement entity) {

        String entitySimpleName = entity.getSimpleName().toString();
        String packageName = processingEnv.getElementUtils()
                .getPackageOf(entity).getQualifiedName().toString();

        GenerateRepository ann = entity.getAnnotation(GenerateRepository.class);
        String repoName = ann.className().isBlank()
                ? entitySimpleName + "Repository"
                : ann.className();

        // ClassName references
        ClassName entityClass    = ClassName.get(packageName, entitySimpleName);
        ClassName ormSessionClass = ClassName.get("com.orm.session", "OrmSession");
        ClassName optionalClass  = ClassName.get(Optional.class);
        ClassName listClass      = ClassName.get(List.class);
        ClassName validatedClass = ClassName.get("com.orm.annotations", "Validated");
        ClassName notNullClass   = ClassName.get("com.orm.annotations", "NotNull");

        // --- field: session ---
        FieldSpec sessionField = FieldSpec
                .builder(ormSessionClass, "session", Modifier.PRIVATE, Modifier.FINAL)
                .build();

        // --- constructor ---
        MethodSpec constructor = MethodSpec.constructorBuilder()
                .addModifiers(Modifier.PUBLIC)
                .addParameter(ormSessionClass, "session")
                .addStatement("this.session = session")
                .build();

        // --- save(entity) ---
        MethodSpec save = MethodSpec.methodBuilder("save")
                .addModifiers(Modifier.PUBLIC)
                .returns(entityClass)
                .addParameter(entityClass, "entity")
                .addStatement("return session.save(entity)")
                .build();

        // --- findById(long id) ---
        TypeName optionalEntity = ParameterizedTypeName.get(optionalClass, entityClass);
        MethodSpec findById = MethodSpec.methodBuilder("findById")
                .addModifiers(Modifier.PUBLIC)
                .returns(optionalEntity)
                .addParameter(long.class, "id")
                .addStatement("return session.findById($T.class, id)", entityClass)
                .build();

        // --- findAll() ---
        TypeName listEntity = ParameterizedTypeName.get(listClass, entityClass);
        MethodSpec findAll = MethodSpec.methodBuilder("findAll")
                .addModifiers(Modifier.PUBLIC)
                .returns(listEntity)
                .addStatement("return session.findAll($T.class)", entityClass)
                .build();

        // --- delete(long id) ---
        MethodSpec delete = MethodSpec.methodBuilder("delete")
                .addModifiers(Modifier.PUBLIC)
                .returns(void.class)
                .addParameter(long.class, "id")
                .addStatement("session.delete($T.class, id)", entityClass)
                .build();

        // --- Javadoc header ---
        String javadoc = "Auto-generated repository for {@link $T}.\n"
                + "Generated by {@code RepositoryProcessor} at compile-time.\n"
                + "\n"
                + "The entity class carries {@code @Validated}, {@code @NotNull}, etc.\n"
                + "which are evaluated at RUNTIME inside {@link com.orm.session.OrmSession}.\n";

        // --- Build class ---
        TypeSpec repoClass = TypeSpec.classBuilder(repoName)
                .addModifiers(Modifier.PUBLIC)
                .addJavadoc(javadoc, entityClass)
                .addField(sessionField)
                .addMethod(constructor)
                .addMethod(save)
                .addMethod(findById)
                .addMethod(findAll)
                .addMethod(delete)
                .build();

        JavaFile javaFile = JavaFile.builder(packageName, repoClass)
                .addFileComment("AUTO-GENERATED — do not edit by hand")
                .indent("    ")
                .build();

        try {
            javaFile.writeTo(processingEnv.getFiler());
            processingEnv.getMessager().printMessage(Diagnostic.Kind.NOTE,
                    "Generated " + packageName + "." + repoName);
        } catch (IOException e) {
            processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR,
                    "Failed to write " + repoName + ": " + e.getMessage());
        }
    }
}
